### ISSUE TITLE
docs(claude-md): add Skill Aliases dispatch table for relocated _internal skills

### ISSUE THREAD

**Issue by kcenon** [kcenon/claude-config#492]
## What

Add a **Skill Aliases dispatch table** to `global/CLAUDE.md` so the 13 workflow skills relocated under `global/skills/_internal/` in #491 (D2, EPIC #454) remain reachable through short keyword commands without per-session priming.

### Background
PR #491 moved 13 SKILL.md files (`branch-cleanup`, `ci-fix`, `doc-index`, `doc-review`, `fleet-orchestrator`, `harness`, `implement-all-levels`, `issue-create`, `issue-work`, `pr-work`, `preflight`, `release`, `research`) under `global/skills/_internal/` to wire up the strict-schema dispatcher (#461). Side effect: Claude Code's user-invocable skill discovery hides directories prefixed with `_`, so slash commands like `/issue-work`, `/pr-work`, `/release` no longer appear in the available-skills catalog and cannot be invoked by users.

### Current behavior
- SKILL.md frontmatter still declares `user-invocable: true` and `disable-model-invocation: true`.
- Files exist at `~/.claude/skills/_internal/<name>/SKILL.md`.
- Slash commands are not surfaced in available skills list.
- `~/.claude/commands/` contains only `_policy.md`, no fallback entries.

### Expected behavior
A user can invoke a relocated skill with a short keyword (e.g. `issue-work #142 --solo`) and Claude reads the matching SKILL.md and executes its body honoring `argument-hint`, `halt_conditions`, and `max_iterations`.

### Scope
- `global/CLAUDE.md`: add a new "Skill Aliases (post-D2 relocation)" section.
- No change to `_internal/` directory layout, no new `commands/` forwarding files.
- Not in scope: re-enabling slash dispatcher (governed by EPIC #454 P4 grace/observation/freeze windows).

### Problem
Three known UX regressions after #491:
1. Daily workflows (`/issue-work`, `/pr-work`, `/release`) silently disappeared.
2. Pattern 1 (full SKILL.md path) is verbose: `~/.claude/skills/_internal/issue-work/SKILL.md ...` per call.
3. Pattern 2 (free-form alias) requires re-priming every new session.

### Impact
Users either fall back to manual procedures or paste long paths. The alias table makes the relocated skills as ergonomic as the previous slash commands.

### Alternatives considered
| Option | Rejected because |
|---|---|
| Move skills back out of `_internal/` | Conflicts with #491 / EPIC #454 strict-schema dispatch design |
| Create 13 forwarding files in `~/.claude/commands/` | Bypasses strict-schema dispatch intent; adds 13 files to maintain |
| Keep as-is, instruct users to use full paths | Rejected as poor UX |

## Where

- `global/CLAUDE.md` (single file changed)
- Optional: bump version footer (`Version: 3.2.0` -> `3.3.0`)

### Implementation
Add a new section under Routing (or at end of file):

```markdown
## Skill Aliases (post-D2 relocation, see #491)

When the user types one of the keywords below as a leading command (with or without arguments and with or without a leading `/`), treat it as an explicit invocation of the corresponding SKILL.md under `~/.claude/skills/_internal/`. Read the SKILL.md, parse arguments per its `argument-hint`, and execute its body honoring `halt_conditions` and `max_iterations`. Do not ask for confirmation; the keyword is the invocation.

| Keyword                | Skill path                                                  |
|------------------------|-------------------------------------------------------------|
| `issue-work`           | `~/.claude/skills/_internal/issue-work/SKILL.md`            |
| `pr-work`              | `~/.claude/skills/_internal/pr-work/SKILL.md`               |
| `release`              | `~/.claude/skills/_internal/release/SKILL.md`               |
| `branch-cleanup`       | `~/.claude/skills/_internal/branch-cleanup/SKILL.md`        |
| `ci-fix`               | `~/.claude/skills/_internal/ci-fix/SKILL.md`                |
| `harness`              | `~/.claude/skills/_internal/harness/SKILL.md`               |
| `research`             | `~/.claude/skills/_internal/research/SKILL.md`              |
| `doc-review`           | `~/.claude/skills/_internal/doc-review/SKILL.md`            |
| `doc-index`            | `~/.claude/skills/_internal/doc-index/SKILL.md`             |
| `preflight`            | `~/.claude/skills/_internal/preflight/SKILL.md`             |
| `issue-create`         | `~/.claude/skills/_internal/issue-create/SKILL.md`          |
| `implement-all-levels` | `~/.claude/skills/_internal/implement-all-levels/SKILL.md`  |
| `fleet-orchestrator`   | `~/.claude/skills/_internal/fleet-orchestrator/SKILL.md`    |

Ambiguity rule: if a keyword appears mid-sentence (not as a leading command), ask whether the user meant the skill or a literal mention.
```

### Acceptance criteria
- [ ] Section added to `global/CLAUDE.md`.
- [ ] All 13 listed skill paths exist on disk after `scripts/sync.sh` deploy.
- [ ] After deploy, `issue-work` typed as a leading command in a fresh session triggers `Read` of the issue-work SKILL.md and follows its procedure.
- [ ] `disable-model-invocation: true` semantics preserved (no auto-trigger from prose mention).
- [ ] No new directories or files outside `global/CLAUDE.md`.
- [ ] CLAUDE.md version footer bumped.

### Test plan
1. Verify each path resolves: `for s in issue-work pr-work release branch-cleanup ci-fix harness research doc-review doc-index preflight issue-create implement-all-levels fleet-orchestrator; do test -f ~/.claude/skills/_internal/$s/SKILL.md && echo OK $s || echo MISSING $s; done`
2. Verify markdown renders cleanly.
3. Manual: in a new session, type `issue-work` and confirm Claude reads the SKILL.md and asks for arguments per its `argument-hint`.

### Rollback
Revert the single commit; no other artifacts touched.

**Comment by kcenon** [comment]
## Implementation Update

| Field | Value |
|-------|-------|
| **PR** | #493 |
| **Branch** | `feature/rs-492-skill-alias-table` |
| **Status** | In Review |

### Summary
Added "Skill Aliases (post-D2 relocation)" section to `global/CLAUDE.md` mapping 13 short keywords (`issue-work`, `pr-work`, `release`, `branch-cleanup`, `ci-fix`, `harness`, `research`, `doc-review`, `doc-index`, `preflight`, `issue-create`, `implement-all-levels`, `fleet-orchestrator`) to their corresponding `SKILL.md` paths under `~/.claude/skills/_internal/`. Includes ambiguity rule for mid-sentence mentions and explicit guidance to honor each SKILL.md's `argument-hint`, `halt_conditions`, and `max_iterations`. Bumped version footer to 3.3.0.

### Verification
- `spec_lint.sh` clean (0 violations across 32 skill files, 2 plugin files, 3 settings files).
- All 13 SKILL.md targets exist on disk and declare `user-invocable: true`.
- Diff is ASCII-only on changed lines.
- Live system updated and `.install-manifest.json` SHA refreshed.

**Comment by kcenon** [comment]
Merged via #493 (squash commit 71dc2362) into develop. Closing manually because GitHub's auto-close keyword fires only on main-targeted merges; this PR targeted develop.
